#!/bin/bash

server=$(dirname "$0")

java \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -noverify \
    -Xmx1G \
    -jar $server/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_1.*.jar \
    -configuration $server/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux/ \
    "$@"
    #"--add-modules=ALL-SYSTEM \
    #"--add-opens java.base/java.util=ALL-UNNAMED \
    #"--add-opens java.base/java.lang=ALL-UNNAMED \
    #"$@"
